apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tensorflow-jupyter
  name: tensorflow-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tensorflow-jupyter
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: tensorflow-jupyter
    spec:
      containers:
        - command:
            - start-notebook.sh
            - --NotebookApp.password=sha1:93ba4185c3ff:2e8d91be9948b031157fffc54d8b6bc7b123fe4a
          image: jupyter/tensorflow-notebook
          imagePullPolicy: IfNotPresent
          name: tensorflow-jupyter
          ports:
            - containerPort: 8888
            - containerPort: 6006
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: tensorflow-jupyter-data-pv-claim
              readOnly: false
          resources: {}
      hostname: tensorflow-jupyter
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: tensorflow-jupyter-data-pv-claim
          persistentVolumeClaim:
            claimName: tensorflow-jupyter-data-pv-claim
      nodeSelector:
        kubernetes.io/hostname: 192.168.1.9
status: {}
